//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toaster_Notification_Signar_R.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int LogID { get; set; }
        public int TerminalID { get; set; }
        public Nullable<int> EventTypeId { get; set; }
        public Nullable<int> FormId { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> SyncDate { get; set; }
    }
}
