//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toaster_Notification_Signar_R.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailServer
    {
        public int ServerId { get; set; }
        public string ServerName { get; set; }
        public string ServerIP { get; set; }
        public int EmailPort { get; set; }
        public string UserName { get; set; }
        public string UserPswd { get; set; }
        public bool UseDefaultCredentials { get; set; }
        public bool EnableSSL { get; set; }
        public bool IsActive { get; set; }
        public Nullable<byte> Priority { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<int> ApprovalStatusId { get; set; }
    }
}
