//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toaster_Notification_Signar_R.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Heartbeat
    {
        public int HeartbeatId { get; set; }
        public int TerminalId { get; set; }
        public System.DateTime HeartbeatTime { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Terminal Terminal { get; set; }
    }
}
