//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toaster_Notification_Signar_R.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalServiceComision
    {
        public int TerminalServiceComisionId { get; set; }
        public int TerminalServiceVendorId { get; set; }
        public decimal StartPrice { get; set; }
        public decimal EndPrice { get; set; }
        public int ComisionTypeId { get; set; }
        public decimal Comision { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ComisionType ComisionType { get; set; }
        public virtual TerminalServiceVendor TerminalServiceVendor { get; set; }
    }
}
