//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toaster_Notification_Signar_R.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public long TransactionHistoryId { get; set; }
        public int TransactionId { get; set; }
        public int TerminalId { get; set; }
        public decimal Amount { get; set; }
        public int ServiceVendorId { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<decimal> Comision { get; set; }
        public int StatusId { get; set; }
        public int PaymentMethodId { get; set; }
        public bool IsPostpaid { get; set; }
        public string Response { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
