//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toaster_Notification_Signar_R.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.TransactionDetails = new HashSet<TransactionDetail>();
            this.TransactionHistories = new HashSet<TransactionHistory>();
        }
    
        public int TransactionId { get; set; }
        public int TerminalId { get; set; }
        public decimal Amount { get; set; }
        public int ServiceVendorId { get; set; }
        public string MobileNumber { get; set; }
        public Nullable<decimal> Commision { get; set; }
        public int StatusId { get; set; }
        public short PaymentMethodId { get; set; }
        public bool IsPostpaid { get; set; }
        public string Response { get; set; }
        public Nullable<byte> RetryCount { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual ServiceVendor ServiceVendor { get; set; }
        public virtual Terminal Terminal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionDetail> TransactionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransactionHistory> TransactionHistories { get; set; }
    }
}
