//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toaster_Notification_Signar_R.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Tasks = new HashSet<Task>();
            this.UserManagers = new HashSet<UserManager>();
            this.UserManagers1 = new HashSet<UserManager>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public long RoleId { get; set; }
        public int CityId { get; set; }
        public Nullable<long> DeptId { get; set; }
        public Nullable<long> SecurityQuestionId { get; set; }
        public string SecurityAnswer { get; set; }
        public Nullable<long> GenderId { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string CNIC { get; set; }
        public string MobileNumber { get; set; }
        public string Address { get; set; }
        public string EmailId { get; set; }
        public string PIN { get; set; }
        public string PINHash { get; set; }
        public Nullable<bool> IsUserLocked { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public string LockedReason { get; set; }
        public Nullable<bool> IsEmailConfirmed { get; set; }
        public Nullable<System.DateTime> EmailConfirmDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> DeleteUserId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteReason { get; set; }
        public int DeviceId { get; set; }
        public int ZoneId { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsNxbUser { get; set; }
        public Nullable<int> AddedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> ApprovalStatusId { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual UserRole UserRole { get; set; }
        public virtual Zone Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserManager> UserManagers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserManager> UserManagers1 { get; set; }
    }
}
